### ISSUE TITLE
Tokenizer preventing some macro expansions

### ISSUE THREAD

**Issue by hackedy** [cornell-netlab/p4pp#6]
In the following program, the first instance of WIDTH gets replaced but the one appearing in the bit<> type does not get replaced. If you look at how it's getting tokenized, it's treating bit<WIDTH> as one big token, so there's never an IDENT token produced for the preprocessor to replace.
```
#define WIDTH 8
WIDTH
bit<WIDTH>
```

**Comment by hackedy** [comment]
Section 6.10 of the C99 standard has a grammar for the preprocessor http://www.open-std.org/jtc1/sc22/WG14/www/docs/n1256.pdf

**Comment by jnfoster** [comment]
This appears to be fixed.
